
import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Jett</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Jett
        </h1>

        <p className={styles.description}>
          The typing game designed to improve programming
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.cardStart}>
            <h3>Start</h3>
            <p className="desc">Begin typing code generated by a corpus imported from real code.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.cardLeaderboard}>
            <h3>Leaderboards</h3>
            <p className="desc">View other coders and their coding speeds, competing for 1st place!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.cardTheme}
          >
            <h3 className={styles.themeh3}>Themes</h3>
            <p className="desc">Change the theme of the website to enhance your coding experience.</p>
          </a>

          <a
            href="https://vercel.com/import?filter=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.cardSetting}
          >
            <h3>Settings</h3>
            <p className="desc">
              Alter the coding language, timing, lenght, corpus generation, etc.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        Copyright &copy; 2020, Jacob Duncan
      </footer>
    </div>
  )
}
