import Head from "next/head";
import Link from "next/link";
import styles from "../../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Jett</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Jett</h1>

        <p className={styles.description}>
          The typing game designed to improve programming
        </p>

        <div className={styles.grid}>
          <Link href="/">
            <div className={styles.cardStart}>
              <h3>Start</h3>
              <p className="desc">
                Begin typing code generated by a corpus imported from real code.
              </p>
            </div>
          </Link>

          <Link href="/leaderboard">
            <div className={styles.cardLeaderboard}>
              <h3>Leaderboards</h3>
              <p className="desc">
                View other coders and their coding speeds, competing for 1st
                place!
              </p>
            </div>
          </Link>

          <Link href="/themes">
            <div className={styles.cardTheme}>
              <h3 className={styles.themeh3}>Themes</h3>
              <p className="desc">
                Change the theme of the website. Coming soon.
              </p>
            </div>
          </Link>

          <Link href="/settings">
            <div className={styles.cardSetting}>
              <h3>Settings</h3>
              <p className="desc">
                Alter the coding language, timing, length, corpus generation,
                etc.
              </p>
            </div>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        Copyright &copy; 2020, Jacob Duncan
      </footer>
    </div>
  );
}
