import Head from "next/head";
import Link from "next/link";
import styles from "../../styles/Home.module.css";
import { FaGithub } from "react-icons/fa";
import HomepageCard from "../../components/homepage-card";

const homepage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Jett</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Jett</h1>

        <p className={styles.description}>
          A typing game to help you type better
        </p>

        {/* Links to the GitHub repository where the code for this project is located*/}
        <Link href="//github.com/jacobduncan00/jett">
          <a
            className={styles.githubLink}
            href="https://github.com/jacobduncan00/jett"
          >
            <FaGithub size={32} />
          </a>
        </Link>

        <div className={styles.grid}>
          <HomepageCard
            linkPath="/game"
            className={styles.cardStart}
            cardTitle="Start"
            cardContents="Begin typing code generated by a corpus imported from real code."
          />

          <HomepageCard
            linkPath="/leaderboard"
            className={styles.cardLeaderboard}
            cardTitle="Leaderboards"
            cardContents="View the speed of other coders. Coming soon."
          />

          <HomepageCard
            linkPath="/themes"
            className={styles.cardTheme}
            cardTitle="Themes"
            cardContents="Change the theme of the website. Coming soon."
          />

          <HomepageCard
            linkPath="/settings"
            className={styles.cardSetting}
            cardTitle=" Settings"
            cardContents="Alter the coding language, timing, length, corpus generation,
                etc."
          />
        </div>
      </main>
    </div>
  );
};

export default homepage;
